# Site settings
title: Visionary Futures Collective
email: visionaryfuturescollective@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/visionary-futures-collective.github.io" # the subpath of your site, e.g. /blog/
url: "localhost:4000" # the base hostname & protocol for your site

twitter_username: CoyoteAndBones
# github_username:

# Build settings
markdown: kramdown
