# Site settings
title: Visionary Futures Collective
description: Jekyll Theme Minimal Resume
baseurl: "/visionary-futures-collective.github.io" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Visionary Futures Collective
user_description: I\'m a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT. I'm one of the two guys behind all the JS related stuff.
user_title: Software Engineer
email: mauriurraco@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum
url: https://visionary-futures-collective.github.io

exclude: ['package.json', 'src' , 'node_modules']
